### ISSUE TITLE
Typo in StudentPortal/pro1/users/models.py  

### ISSUE THREAD

**Issue by gopavasanth** [monsij/StudentPortal#8]
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/gopavasanth/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/gopavasanth/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/gopavasanth/.local/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/gopavasanth/.local/lib/python3.5/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/gopavasanth/.local/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/gopavasanth/Desktop/StudentPortal/pro1/users/models.py", line 11
    return f'{self.user.username} Profile'

**Hack**: Change  "return f'{self.user.username}" Profile' to  "return '{self.user.username} Profile'"

This Solved my Issue !!

**Comment by monsij** [comment]
assigned @arpit3018

**Comment by nguptaa** [comment]
Please assign me this issue

**Comment by monsij** [comment]
Assigned @nguptaa

**Comment by monsij** [comment]
Sorry @nguptaa , Let @arpit3018 wind up his work with this first

**Comment by arpit3018** [comment]
Hey. do we need that usernames in the admin panel like this? Look the below link for the image
[https://ibb.co/w6kbT9L](url)

**Comment by arpit3018** [comment]
![screenshot from 2018-12-06 21-11-38](https://user-images.githubusercontent.com/33262874/49594669-689af400-f99c-11e8-96d4-1be3d5662abe.png)

**Comment by monsij** [comment]
Need means?...Do you want to alter the formatting? @arpit3018

**Comment by arpit3018** [comment]
I mean to save that earlier it is showing some meaning less info on  **f'{self.user.username} Profile'** but after change it to **self.user.username**. It now shows the name of the user. So is it right or should I change something?

**Comment by monsij** [comment]
Please put the screenshots in either case 🍶

**Comment by arpit3018** [comment]
![screenshot from 2018-12-06 21-52-37](https://user-images.githubusercontent.com/33262874/49596866-4d7eb300-f9a1-11e8-9d9a-c976c0d35f78.png)
![Uploading Screenshot from 2018-12-06 21-52-48.png…]()

**Comment by arpit3018** [comment]
![screenshot from 2018-12-06 21-52-37](https://user-images.githubusercontent.com/33262874/49596866-4d7eb300-f9a1-11e8-9d9a-c976c0d35f78.png)
![screenshot from 2018-12-06 21-52-48](https://user-images.githubusercontent.com/33262874/49596869-4e174980-f9a1-11e8-81b0-22dad909ff8f.png)

**Comment by monsij** [comment]
Yup. It's working fine right with the existing code?

**Comment by arpit3018** [comment]
Nope. I Changed it to **self.user.username + ' Profile'**

**Comment by monsij** [comment]
But it's working fine with `f'{self.user.username} Profile'` for me

**Comment by monsij** [comment]
Marking this issue as stale.Will continue on it later . Thanks @arpit3018

**Comment by arpit3018** [comment]
This is not working for me. It is showing the error which was mention above by @gopavasanth. Have a look at it @monsij

**Comment by monsij** [comment]
Unless it shows error during deployment..it cant be changed

**Comment by arpit3018** [comment]
No issues. Thanks
